### ISSUE TITLE
Add Linkdn in  Footer 

### ISSUE THREAD

**Issue by satyamyadav979** [AOSSIE-Org/website#100]
## Description
Add a LinkedIn icon and link to the footer of the website. This will allow users to easily find and follow our LinkedIn page.

## Tasks
- [ ] Design a LinkedIn icon that matches the style of the existing social media icons in the footer.
- [ ] Add the LinkedIn icon to the footer.
- [ ] Ensure the LinkedIn icon links to our LinkedIn page: [https://www.linkedin.com/company/your-company](https://www.linkedin.com/company/your-company)
- [ ] Test the new icon and link to ensure they work correctly on both desktop and mobile versions of the site.

## Additional Notes
- Ensure the icon is appropriately sized and spaced in the footer.
- Follow the existing color scheme and design guidelines for consistency.

## Reference
<img width="1120" alt="Screenshot 2024-08-04 at 12 18 22 PM" src="https://github.com/user-attachments/assets/012e4003-30d8-4a11-8c59-59eeec5f66ba">

**Comment by satyamyadav979** [comment]
@ceilican  please assign this issue to me , As I already working on it

**Comment by Harsh10022004** [comment]
@ceilican i would like to work on this issue
